ANALYSIS_THRESHOLDS = {
    'BLUNDER_THRESHOLD':        200,
    'MISTAKE_THRESHOLD':        100,
    'INACCURACY_THRESHOLD':      50,
    'EXCELLENT_MOVE_THRESHOLD':  10,
    'BLUNDER_WIN_PROB_DROP':     15,
    'MISTAKE_WIN_PROB_DROP':      7,
    'INACCURACY_WIN_PROB_DROP':   3,
}
